package main

import "fmt"

// #cgo CFLAGS: -DWITH_APPARMOR
// #include "libaudit.h"
// struct msg_type {
//	int num;
//	char* name;
// };
// struct msg_type msg_types[] = {
// #define _S(num, name) { (num), (name) },
// #include "msg_typetab.h"
// #undef _S
// };
import "C"

func main() {
	fmt.Println(
`// This file is automatically generated. Re-generate by running "make lookup.go"
package main

var AuditMessageTypeNames = map[uint16]string{`,
	)
	for _, msgType := range C.msg_types {
		fmt.Print("\t", msgType.num, ": \"", C.GoString(msgType.name), "\",\n")
	}
	fmt.Println("}")
}
