name: gofmt
on:
  push:
  pull_request:
    paths:
      - '.github/workflows/gofmt.yml'
      - '**.go'
jobs:

  gofmt:
    name: Run gofmt
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go Stable
      uses: actions/setup-go@v5
      with:
        go-version: stable
        check-latest: true
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: gofmt
      run: |
        if [ "$(find . -iname '*.go' | xargs gofmt -l)" ]
        then
          find . -iname '*.go' | xargs gofmt -d
          exit 1
        fi
